import { config } from "@/core/config";
import { defineCommand } from "@/core/types";

const p = config.prefix;

export default defineCommand({
  name: "gamerules",
  description: "Daftar aturan main game + cara pakai",
  handler: async (_sock, msg) => {
    const text = [
      "🎮 *ATURAN GAME SEAAVEYBOT*",
      "",
      `1) *Math* (${p}math)`,
      "- Bot kirim soal hitung.",
      "- Jawab langsung di chat (tanpa prefix).",
      "- Batas waktu 30 detik.",
      "",
      `2) *Tebak Kata* (${p}tebakkata)`,
      "- Susun huruf acak jadi kata benar.",
      "- Jawab langsung di chat (tanpa prefix).",
      "- Batas waktu 60 detik.",
      "",
      `3) *Trivia* (${p}trivia)`,
      "- Bot kirim pertanyaan umum.",
      "- Jawab langsung di chat (tanpa prefix).",
      "- Batas waktu 30 detik.",
      "",
      `4) *Tebak Bendera* (${p}tebakbendera)`,
      "- Tebak negara dari emoji bendera.",
      "- Jawab langsung di chat (tanpa prefix).",
      "- Batas waktu 30 detik.",
      "",
      `5) *Tebak Gambar* (${p}tebakgambar)`,
      "- Tebak jawaban dari gambar + clue.",
      "- Jawab langsung di chat (tanpa prefix).",
      "- Batas waktu 60 detik.",
      "",
      `6) *Family100* (${p}family100)`,
      "- Khusus grup.",
      "- Tebak semua jawaban survey.",
      "- Jawab langsung di grup (tanpa prefix).",
      "- Batas waktu 120 detik.",
      "",
      `7) *Tebak Angka* (${p}tebakangka)`,
      "- Mulai: ketik perintah tanpa angka.",
      `- Tebak: ${p}tebakangka [1-100].`,
      `- Menyerah: ${p}tebakangka nyerah.`,
      "- Maks 10 percobaan / 120 detik.",
      "",
      `8) *Quiz* (${p}quiz)`,
      "- Bot kirim soal pilihan ganda.",
      `- Jawab: ${p}quiz A/B/C/D.`,
      "- Batas waktu 30 detik.",
      "",
      `9) *Hangman* (${p}hangman)`,
      "- Tebak huruf satu-satu.",
      `- Jawab: ${p}hangman [huruf].`,
      `- Menyerah: ${p}hangman nyerah.`,
      "- 6 nyawa / 120 detik.",
      "",
      `10) *TicTacToe* (${p}tictactoe)`,
      "- Lawan bot.",
      `- Jalan: ${p}tictactoe [1-9].`,
      `- Menyerah: ${p}tictactoe nyerah.`,
      "- Batas waktu 120 detik.",
      "",
      `11) *Wordchain* (${p}wordchain)`,
      "- Sambung kata: huruf awal = huruf akhir kata sebelumnya.",
      `- Jawab: ${p}wordchain [kata].`,
      `- Menyerah: ${p}wordchain nyerah.`,
      "- Minimal 3 huruf / 120 detik per giliran.",
      "",
      `12) *Quick Games* (${p}slot, ${p}dice, ${p}coinflip, ${p}suit)`,
      "- Slot: putar sekali, XP sesuai hasil.",
      `- Dice: ${p}dice [1-6].`,
      `- Coinflip: ${p}coinflip heads/tails.`,
      `- Suit: ${p}suit batu/gunting/kertas.`,
      "",
      "Tips:",
      `- Lihat semua command game: ${p}menu game`,
      `- Lihat aturan ini lagi: ${p}gamerules`,
    ].join("\n");

    await msg.reply(text);
  },
});
